### ISSUE TITLE
Services / News - device: Stretched post featured image

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/NV-Global-Tiling#101]
Affected device(s): S4, iPodtouch5
Affected page(s):
Services page
Services Single page
News Page
News Single page

**Comment by romatitan** [comment]
Kindly check again on Services Single page - landscape view

**Comment by christiancebudigital** [comment]
these are image that are being cropped due to big resolution and cant fit on one page.

**Comment by romatitan** [comment]
Kindly check again on 
Services listing page - landscape view
News listing page - landscape view

**Comment by christiancebudigital** [comment]
this is an add image size function for post thumbnails, please advise on what function to use.

**Comment by romatitan** [comment]
Change width 100% to max width 100%
text-align to center

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/11054003/6d0627b4-87a1-11e5-9d81-f48b3d6536e3.jpg)

for wrapper
text-align:center

**Comment by christiancebudigital** [comment]
this is not not a function and images are not blurred, this is considered as fixed, please don't advice on what css to use.

**Comment by romatitan** [comment]
Hi kindly check this link as reference.
http://thewillandprobatecentre.stage.titanweb.com.au/costs/

Avoid using !important
I've updated the bug title as well.

**Comment by romatitan** [comment]
@christiancebudigital 
Hi kindly check this link as reference.
http://thewillandprobatecentre.stage.titanweb.com.au/costs/

Avoid using !important
I've updated the bug title as well.

**Comment by bernardtitan** [comment]
Christian, the images are being stretched, they're clearly pixelated even on the desktop. 

Knowing the original dimensions of that image, an image of that size does not become pixelated unless it was shrunk and stretched again afterwards. Which I have confirmed by reducing my window size and viewing the image afterwards whose dimensions are 225x225 being stretched to 681x681.

Q.E.D.: Fix the damn bug, we're wasting time here.

The above CSS code was given under the advice of a developer here, and truth be told, if it can be handled by CSS it would be better than if we used a function for performance reasons.

Now, I would appreciate it if don't snap at my people for giving advice, because you were asking for advice not two posts above that, even if it's not the exact answer you were looking for. It's unprofessional. As I've said before, if you're not willing to listen, don't ask.
